[workspace]
members = ["decompose", "toml-edit-derive/core", "toml-edit-derive/derive-macro"]

[package]
name = "lazy-java"
version = "0.1.0"
edition = "2024"

authors = ["lucasvanderwielen@icloud.com"]
description = "Simple and Intuitive Java build tool"
readme = "README.md"
repository = "https://github.com/LucasVand/lazy-java"
license = "MIT" 

keywords = ["java", "build", "tool", "utility", "cargo"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
colored = "3.1.1"
filetime = "0.2.27"
inquire = "0.9.3"
log = "0.4"
quick-xml = { version = "0.39.2", features = ["serialize"] }
regex = "1.10"
reqwest = { version = "0.13.3", features = ["blocking"] }
tokio = { version = "1.50.0", features = ["full"]}
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
env_logger = "0.11.10"
maven-version-rs = "0.1.0"
toml = "1.1.2"
parking_lot = "0.12.5"
strum = { version = "0.28.0", features = ["derive"] }
toml_edit = { version = "0.25", features = ["serde"] }
decompose = { path = "decompose", version = "0.1.0"  }
globset = "0.4.18"
walkdir = "2.5.0"
zip = "8.6.0"
toml-edit-derive = { path = "toml-edit-derive/core", version = "0.1.0"}
same-file = "1.0.6"

[dev-dependencies]
tempfile = "3.27.0"
assert_cmd = "2"
predicates = "3"
fs_extra = "1.3"
insta = { version = "1", features = ["yaml"] }
