use predicates::prelude::predicate;

use crate::support::{lazy_java, Project};

#[test]
fn auto_value_generates_code_and_runs() -> Result<(), Box<dyn std::error::Error>> {
    let p = Project::from_fixture("auto-value")?;
    let dest = &p.dir;

    // Step 1: Add the annotation dependency
    lazy_java(dest)?
        .args([
            "add",
            "com.google.auto.value",
            "auto-value-annotations",
            "1.11.1",
        ])
        .assert()
        .success();

    // Step 2: Add the annotation processor dependency
    lazy_java(dest)?
        .args(["add", "com.google.auto.value", "auto-value", "1.11.1"])
        .assert()
        .success();

    assert!(
        dest.join("lazy-java.lock").exists(),
        "lock file should exist after add"
    );

    // Step 3: Build — triggers AutoValue annotation processing
    lazy_java(dest)?.args(["build"]).assert().success();

    // Generated class was created by AutoValue
    assert!(
        dest.join("target")
            .join("bin")
            .join("app")
            .join("AutoValue_Person.class")
            .exists(),
        "AutoValue_Person.class should have been generated by annotation processing"
    );

    // Person class was compiled
    assert!(
        dest.join("target")
            .join("bin")
            .join("app")
            .join("Person.class")
            .exists(),
        "Person.class should exist"
    );

    // Main class was compiled
    assert!(
        dest.join("target")
            .join("bin")
            .join("app")
            .join("Main.class")
            .exists(),
        "Main.class should exist"
    );

    // Step 4: Run and verify the generated code produces expected output
    lazy_java(dest)?
        .args(["run", "--no-build", "app.Main"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Alice"))
        .stdout(predicate::str::contains("30"));

    Ok(())
}